version: "3"
services: 
  app:
    container_name: zoom
    restart: always
    build: .
    ports:
      # HOST:CONTAINER
      - 3000:3000
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: